image: python:3.9

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y python3 python3-pip
    - pip3 install -r requirements.txt
    - python3 manage.py collectstatic --noinput
    - python3 manage.py migrate
  artifacts:
    paths:
      - public
  only:
    - master
